// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef elevator_changes_h
#define elevator_changes_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Value_Output.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
Fl_Window* make_window();
#endif
